let li = document.createElement('li');
let li2 = document.createElement('li');
let li3 = document.createElement('li');
li.textContent = "Html";
li2.textContent = "css";
li3.textContent = "javascript";
document.querySelector('ul').appendChild(li);
document.querySelector('ul').appendChild(li2);
document.querySelector('ul').appendChild(li3);
// question 2
let div = document.querySelector('div');
let p1 = document.createElement('p');
let p2 = document.createElement('p');
let p3 = document.createElement('p');
p1.textContent = "name:rahul";
p2.textContent = "age:20";
p3.textContent = "course:javscript";
document.querySelector('div').appendChild(p1);
document.querySelector('div').appendChild(p2);
document.querySelector('div').appendChild(p3);